
def get_brands():
    return  [
        "Insignia", 
        "Dynex",
        "Naxa",
        "Coby", 
        "SunBriteTV",

    "Acer Inc.",
    "Admiral",
    "Aiwa",
    "Akai",
    "Alba",
    "Amstrad",
    "Andrea Electronics",
    "Apex Digital",
    "Apple Inc.",
    "Arcam",
    "Arise India",
    "AGA AB",
    "Audiovox",
    "AWA",
    "Baird",
    "Bang & Olufsen",
    "Beko",
    "BenQ",
    "Binatone",
    "Blaupunkt",
    "BPL Group",
    "Brionvega",
    "Bush",
    "Canadian General Electric (CGE)",
    "Changhong",
    "ChiMei",
    "Compal Electronics[1]",
    "Conar Instruments",
    
    "Continental Edison",
    "Cossor",
    "Craig",
    "Curtis Mathes Corporation",
    "Daewoo",
    "Dell",
    "Delmonico International Corporation",
    "DuMont Laboratories",
    "Durabrand",
    "Dynatron",
    "English Electric",
    "English Electric Valve Company",
    "EKCO",
    "Electrohome",
    "Element Electronics",
    "Emerson Electric",
    "EMI",
    "Farnsworth",
    "Ferguson Electronics",
    "Ferranti",
    "Finlux (Vestel)",
    "Fisher Electronics",
    "Fujitsu",
    "Funai",
    "Geloso",
    "General Electric",
    "General Electric Company",
    "GoldStar",
    "Goodmans Industries",
    "Google",
    "Gradiente",
    "Grundig",
    "Haier",
    "Hallicrafters",
    "Hannspree",
    "Heath Company/Heathkit",
    "Hinari Domestic Appliances",
    "HMV",
    "Hisense",
    "Hitachi",
    "Hoffman Television (Cortron Ind)",
    "Itel",
    "ITT Corporation",
    "Jensen Loudspeakers",
    "JVC",
    "Kenmore",
    "Kent Television",
    "Kloss Video",
    "Kogan",
    "Kolster-Brandes",
    "Konka",
    "Lanix",
    "Le.com",
    "LG",
    "Loewe",
    "Luxor",
    "Magnavox",
    "Marantz",
    "Marconiphone",
    "Matsui",
    "Memorex",
    "Micromax",
    "Metz",
    "Mitsubishi",
    "Mivar",
    "Motorola",
    "Muntz (Howard Radio)",
    "Murphy Radio",
    "NEC",
    "Nokia",
    "Nordmende",
    "Onida",
    "Orion (Hungary)",
    "Orion (Japan)",
    "Packard Bell, Teledyne Packard Bell",
    "Panasonic",
    "Pensonic",
    "Philco (Philco-Ford)",
    "Philips",
    "Pioneer",
    "Planar Systems",
    "Polaroid",
    "ProLine",
    "ProScan",
    "Pye",
    "Pyle USA",
    "Quasar",
    "RadioShack",
    "Rauland-Borg",
    "RCA",
    "Realistic",
    "Rediffusion",
    "SABA",
    "Salora",
    "Salora International",
    "Samsung",
    "Sansui",
    "Sanyo",
    "Schneider Electric",
    "Seiki",
    "Sèleco",
    "Setchell Carlson",
    "Sharp",
    "Siemens",
    "Skyworth",
    "Sony",
    "Soyo",
    "Stromberg-Carlson",
    "Supersonic",
    "Sylvania",
    "Tandy",
    "Tatung Company",
    "TCL Corporation",
    "Technics",
    "TECO",
    "Teleavia",
    "Telefunken",
    "Teletronics",
    "Thomson SA",
    "Thorn Electrical Industries",
    "Thorn EMI",
    "Toshiba",
    "TPV Technology",
    "TP Vision",
    "Ultra",
    "United States Television Manufacturing Corp.",
    "Vestel",
    "Videocon",
    "Videoton",
    "ViewSonic", #Added by Naim 
    "Vizio",
    "Vu Televisions",
    "Walton",
    "Westinghouse Electric Corporation",
    "Westinghouse",
    "White-Westinghouse",
    "Xiaomi",
    "Zanussi",
    "Zenith Radio",
    "Zonda"
]